.TH "C:/Users/Михаил/Documents/Visual Studio 2013/Projects/laba2/laba2 Directory Reference" 3 "Sun Mar 1 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Михаил/Documents/Visual Studio 2013/Projects/laba2/laba2 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlaba2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstdafx\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstdafx\&.h\fP"
.br
.ti -1c
.RI "file \fBtargetver\&.h\fP"
.br
.in -1c
