.TH "C:/Users/Михаил/Documents/Visual Studio 2013/Projects/laba2/laba2/stdafx.cpp" 3 "Sun Mar 1 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Михаил/Documents/Visual Studio 2013/Projects/laba2/laba2/stdafx.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
