.TH "C:/Users/Михаил/Documents/Visual Studio 2013/Projects/laba2/laba2/targetver.h" 3 "Sun Mar 1 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Михаил/Documents/Visual Studio 2013/Projects/laba2/laba2/targetver.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SDKDDKVer\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
